{% set version = "2.1.0" %}

package:
  name: ocgis
  version: {{ version }}

source:
  fn: ocgis-{{ version }}.tar.gz
  url: https://github.com/NCPP/ocgis/archive/v{{ version }}.tar.gz
  sha256: 9cd680ce2bf8a25f50c4123145f16806b63484bc1b5d10408acd1d144f828eaa

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - gdal 2.2*
    - pyproj
    - shapely
    - fiona
    - six
    - numpy
    - netcdf4
  run:
    - python
    - cf_units
    - fiona
    - gdal 2.2*
    - netcdf4
    - numpy
    - shapely
    - rtree
    - pyproj
    - mpi4py

test:
  requires:
    - nose
    - mock
  imports:
    - ocgis
  commands:
    - ocli chunked_rwg --help

about:
  home: http://ocgis.readthedocs.io/en/latest/
  license: NCSA
  summary: 'OpenClimateGIS (OCGIS) provides geoprocessing and calculation tools for spatiotemporal datasets.'

extra:
  recipe-maintainers:
    - bekozi
    - ocefpaf
