{% set version = "1.3.2" %}

package:
  name: ocgis
  version: {{ version }}

source:
  fn: ocgis-{{ version }}.tar.gz
  url: https://github.com/NCPP/ocgis/archive/v{{ version }}.tar.gz
  sha256: b24f853d5f37ea2a809ec2d0cdebcaa4c21c80624a07a720212d3f3d0600b35f

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cf_units
    - fiona
    - netcdf4
    - numpy
    - shapely
    - rtree

test:
  requires:
    - nose
  imports:
    - ocgis

about:
  home: http://ocgis.readthedocs.io/en/latest/
  license: NCSA
  summary: 'OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.'

extra:
  recipe-maintainers:
    - bekozi
    - ocefpaf
