# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HESuRGxKs5dPQkzFBFrfo05tn1/M5QEGhFJfY7stGNnGR1Azh/yP/HcnNkkAuD/LiRsurq0RhAWdomI7nh+CJLNzJlar+fe5uwr0QE6rZHOCFyMOTbfnqKLqm9Qc8f5/UoOfrrp+dZUoFjINHtgY2Ce7UA6ubFZF3nfJdHw6OabWqQrTvq2vE+WleZpkBiQNGcbjNenByvoBtdlBDt/D0EHe3HLCj9bYIldn/CI4F3yGG34lEGvQ7Uczkpn2be7RA2SakmA06dEqTm6Xdlj72bzNA3ZfSjOMTRJyzH4Sl7q7vQRWym/73mVapQhhYHshbkA0s2hMJsRKPTqaMPJIyBzg9JprcPWmIIEcIdywSF1dgp3wXyWgC/sWusidej3D/KQKJoPoWw/Hd36poP00R/PBIscdhf/JnZcRGpEL5yOoG38mVHBCwyHaSU3g+PaZIRO8FLeAGtv+ZaxJ1jqUDx1O62piJoMBtwDvOc8nIJke8QQMAOFD/SicW+RovgNOzjqoLkS2NGktJDGfLoehBPNJ9bUGA+0AQu/kFhymdioSnAlPeKMTWzKOc0qz1Mgp2bH7ilnBx+V3nmrGqePckRQ5isuFnUq1YXIgGLXUAX1NoPk/C8IQUrfrI+DqZHdXHl8vTIUV41mkQNFcNeMwygmwrxrnASLgcya5iWnhtDE="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
