travis:
  secure:
    BINSTAR_TOKEN: HESuRGxKs5dPQkzFBFrfo05tn1/M5QEGhFJfY7stGNnGR1Azh/yP/HcnNkkAuD/LiRsurq0RhAWdomI7nh+CJLNzJlar+fe5uwr0QE6rZHOCFyMOTbfnqKLqm9Qc8f5/UoOfrrp+dZUoFjINHtgY2Ce7UA6ubFZF3nfJdHw6OabWqQrTvq2vE+WleZpkBiQNGcbjNenByvoBtdlBDt/D0EHe3HLCj9bYIldn/CI4F3yGG34lEGvQ7Uczkpn2be7RA2SakmA06dEqTm6Xdlj72bzNA3ZfSjOMTRJyzH4Sl7q7vQRWym/73mVapQhhYHshbkA0s2hMJsRKPTqaMPJIyBzg9JprcPWmIIEcIdywSF1dgp3wXyWgC/sWusidej3D/KQKJoPoWw/Hd36poP00R/PBIscdhf/JnZcRGpEL5yOoG38mVHBCwyHaSU3g+PaZIRO8FLeAGtv+ZaxJ1jqUDx1O62piJoMBtwDvOc8nIJke8QQMAOFD/SicW+RovgNOzjqoLkS2NGktJDGfLoehBPNJ9bUGA+0AQu/kFhymdioSnAlPeKMTWzKOc0qz1Mgp2bH7ilnBx+V3nmrGqePckRQ5isuFnUq1YXIgGLXUAX1NoPk/C8IQUrfrI+DqZHdXHl8vTIUV41mkQNFcNeMwygmwrxrnASLgcya5iWnhtDE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
