travis:
  secure:
    BINSTAR_TOKEN: lOtxexwEbclNidLppQhbxmj00m5XQwCo0hN/YvzcxVeXlhvbLEOFg87H8lSc5mb+ADEwrTaNFlh8DqUrhEm3L248UcQF+kyay8fpsWi9kFgsR3/xTQ2vTKxyCpH4TBZI472VAOtVCK+lFyrCTEnDiF+kG6JGtq0cBAHkytnB3QoVSdj4PXxyAlk7TphGan4Qg9TFhjPvep5VANZRK2K909lEXLWE2JdeNGx/FD92M6SRfO5Hu/3owf3PtP575ZLNoQOaTtBsJ1IGYWOHF4keiJpIGFA6C2lO6OyjwdSaX9oRhTzeOxeBbPdsPLrfneO5u+5OBRbhaq1nY830QL0PjPw1mlObAa8tknCkQ5LdEQcsUDdn9N7bi68YPg+9NcIlHYdhFttFOk4KjuRF1t3B8jPt/xRw8U+ojwI+FzDNy6Vy6jlbneMD0dzBjso32vWhTlsGw0RksC8b85W3b96MR4DqZUp7A4fWSAF1Bgtxd+siaH7ZbPmVyuSdJ8NP+xHAdhsIM6+EcOjZd1Fp2B8Cy8odih/akxvSLD+byfZf8WMR3isPf5HDlzThf53A49mFfhxig1Frz3sn4ncHkgkmK3ADeUoX0quNY5ElJIbi59hp3IrJsQRayZhiEObxO9VwW2Q4gB6T6sKhvxhYtDZgl1zRTQoE9eLO0XAcBEnzNsI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
